dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install "cryptography<2.9"; fi
  - pip install -r requirements.txt
  - pip install coveralls
env:
  global:
    - HTTPBIN=httpbin.bemisc.com
    - REPO_URL_COLONY="https://colony.bemisc.com/"
    - REPO_USERNAME=root
    - secure: l7gFGuBD1TmMF7nCnkDcsm6LCbOt5s7S6cO6YdXD35HebULtxWbbxNGPehxcZ03AbBX/arLFeowHqNgd9gPnWenzErkUGVu3uF1Q5St46Tb3p9Ga3obnsJPh3bBw8YWElzp6unZy+XpSpqsxTTPqAPC6ZhVAzKNGfcXSeGgAPLE=
script: PLUGIN_PATH="./*/src;./*/*src" coverage run setup.py test
after_success:
  - coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then cpm upload "./*/*/*_plugin.py" colony; fi
