dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy2.7-5.9.0"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install "cryptography<2.9"; fi
  - pip install -r requirements.txt
  - pip install coveralls
env:
  global:
    - HTTPBIN=httpbin.bemisc.com
script: PLUGIN_PATH="./*/src;./*/*src" coverage run setup.py test
after_success:
  - coveralls
