sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.7.0"
  - "pypy3-2.4.0"
  - "pypy3-5.7.0"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install colony
env:
  global:
    - HTTPBIN=httpbin.stage.hive.pt
    - REPO_URL_COLONY="https://colony.bemisc.com/"
    - REPO_USERNAME=root
    - secure: l7gFGuBD1TmMF7nCnkDcsm6LCbOt5s7S6cO6YdXD35HebULtxWbbxNGPehxcZ03AbBX/arLFeowHqNgd9gPnWenzErkUGVu3uF1Q5St46Tb3p9Ga3obnsJPh3bBw8YWElzp6unZy+XpSpqsxTTPqAPC6ZhVAzKNGfcXSeGgAPLE=
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then PLUGIN_PATH="./*/src;./*/*src" coverage run setup.py test; else PLUGIN_PATH="./*/src;./*/*src" python setup.py test; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then cpm upload "./*/*/*_plugin.py" colony; fi
