##################################################
# StockQuote_services.py
# generated by ZSI.generate.wsdl2python
##################################################


from StockQuote_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

# Locator
class StockQuoteLocator:
    StockQuoteSoap_address = "http://www.webservicex.net/stockquote.asmx"
    def getStockQuoteSoapAddress(self):
        return StockQuoteLocator.StockQuoteSoap_address
    def getStockQuoteSoap(self, url=None, **kw):
        return StockQuoteSoapSOAP(url or StockQuoteLocator.StockQuoteSoap_address, **kw)

# Methods
class StockQuoteSoapSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: GetQuote
    def GetQuote(self, request):
        if isinstance(request, GetQuoteSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.webserviceX.NET/GetQuote", **kw)
        # no output wsaction
        response = self.binding.Receive(GetQuoteSoapOut.typecode)
        return response

GetQuoteSoapIn = ns0.GetQuote_Dec().pyclass

GetQuoteSoapOut = ns0.GetQuoteResponse_Dec().pyclass
