<div id="wiki-footer">
    <div class="wiki-footer-contents">
        <div id="wiki-footer-contents-left">
            <div class="logo-image">
                <a href="http://getcolony.com"><img src="${out_none value=base_path /}${out_none value=instance_name /}/images/powered_by_colony.png"/></a>
            </div>
            <div class="separator">
                <img src="${out_none value=base_path /}${out_none value=instance_name /}/images/separator.png"/>
            </div>
            <div class="text-contents">
                Document generated by colony framework in ${out_none value=generation_time xml_escape=True /} seconds<br />
                Copyright <a href="http://hive.pt">Hive Solutions Lda.</a> distributed under <a href="http://creativecommons.org/licenses/by-sa/3.0"> Creative Commons License</a>
            </div>
        </div>
        <div id="wiki-footer-contents-right">
            <div id="wiki-options-button" class="wiki-button wiki-button-grey">Options</div>
        </div>
    </div>
</div>
