<div id="wiki-footer">
    <div class="wiki-footer-contents">
       <div id="wiki-footer-contents-left">
            <div class="text-contents">
                Document generated by colony framework in ${out_none value=generation_time xml_escape=True /} seconds<br />
                Copyright <a href="http://hive.pt">Hive Solutions Lda.</a> distributed under <a href="http://creativecommons.org/licenses/by-sa/3.0"> Creative Commons License</a>
            </div>
        </div>
        <div id="wiki-footer-contents-right">
            <div class="text-contents">Document generated in ${datetime /}</div>
        </div>
    </div>
</div>
