<div id="wiki-footer">
    <div class="wiki-footer-contents">
        <div class="logo-image">
            <a href="http://getcolony.com"><img src="images/powered_by_colony.png"/></a>
        </div>
        <div class="separator">
            <img src="images/separator.png"/>
        </div>
        <div class="text-contents">
            Document generated by colony framework in ${out_none value=generation_time xml_escape=True /} seconds<br/>
            Copyright <a href="http://www.hive.pt">Hive Solutions Lda.</a> distributed under <a href="http://creativecommons.org/licenses/by-sa/3.0"> Creative Commons License</a>
        </div>
    </div>
</div>
