name: Deploy Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [2.7]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: pip install -r requirements.txt
        if: matrix.python-version != '2.7'
      - run: pip install -r requirements.py2.txt
        if: matrix.python-version == '2.7'
      - run: python setup.py test
        env:
          HTTPBIN: httpbin.bemisc.com
          PLUGIN_PATH: ./*/src;./*/*src
      - run: cpm upload "./*/*/*_plugin.py"
        env:
          REPO_URL_COLONY: https://colony.bemisc.com/
          REPO_USERNAME: ${{ secrets.COLONY_REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.COLONY_REPO_PASSWORD }}
